eureka:
  client:
    register-with-eureka: true
  service-url: http://localhost:8761/eureka/
spring:
  application:
    name: Onboarding
  datasource:
    url: jdbc:h2:./rogersDb
    username: roger
    password: telecom

  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true


server:
  port: 10001
